#!/bin/bash

sgdisk -Z /dev/sda
sgdisk -n 0:0:+513M -t 0:ef00 -c 0:"boot" /dev/sda
sgdisk -n 0:0:0 -t 0:8300 -c 0:"rootfs" /dev/sda
sgdisk -p /dev/sda
partprobe
fdisk -l /dev/sda
exit
unit: sectors
/dev/sda1 : start=2048, size=999424, type=ef
/dev/sda2 : start=1001472, size=32550912, type=83
